# Generated by Django 3.1.5 on 2021-02-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanclub', '0004_chatroom_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='desc',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
