# Generated by Django 3.1.5 on 2021-03-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanclub', '0005_chatroom_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='imageMsg',
            field=models.ImageField(blank=True, upload_to='msg_image'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
