# Generated by Django 3.1.5 on 2021-03-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanclub', '0006_auto_20210310_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='cover',
            field=models.ImageField(blank=True, upload_to='group_cover'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='icon',
            field=models.ImageField(blank=True, upload_to='group_icon'),
        ),
    ]
