# Generated by Django 3.1.5 on 2021-03-11 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanclub', '0008_bio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friends',
        ),
    ]
